version: '3'
services:
        fluentd:
                build: 
                        context: ./fluentd_sv
                        dockerfile: Dockerfile
                container_name: fluentd
                restart: always
                environment:
                        - FLUENTD_CONF=fluentd.conf
                ports:
                        - 24224:24224
                        - 24224:24224/udp
                volumes:
                        - ./fluentd_sv/conf/:/fluentd/etc:ro
        jupyter_sv:
                image: jupyter/scipy-notebook
                container_name: jupyter_sv
                restart: always
                environment:
                        - JUPYTER_ENABLE_LAB=yes
                entrypoint: >
                        jupyter-lab
                        --ip 0.0.0.0
                        --port 8000
                        --no-browser
                        --notebook-dir /home/juvyan
                        --config /etc/jupyter/jupyter_lab_config.py
                        --ServerApp.password ${JUPYTER_PASSWD}
                ports:
                        - 8000:8000
                volumes:
                        - ./jupyter/:/etc/jupyter:ro
                        - ./raid_fs:/home/juvyan
                logging:
                        driver: fluentd
                        options:
                                fluentd-address: localhost:24224
                                tag: docker.{{.Name}}
                depends_on:
                        - fluentd

        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
                container_name: elasticsearch
                environment:
                        - "discovery.type=single-node"
                        - "xpack.security.enabled=false"
                expose:
                        - 9200
                ports:
                        - 9200:9200
                logging:
                        driver: fluentd
                        options:
                                fluentd-address: localhost:24224
                                tag: docker.{{.Name}}
                depends_on:
                        - fluentd
        kibana:
                image: docker.elastic.co/kibana/kibana:8.1.1
                container_name: kibana
                ports:
                        - 5601:5601
                logging:
                        driver: fluentd
                        options:
                                fluentd-address: localhost:24224
                                tag: docker.{{.Name}}
                depends_on:
                        - fluentd
                        - elasticsearch
        samba:
                image: dperson/samba
                container_name: samba
                ports:
                        - 137:137/udp
                        - 138:138/udp
                        - 139:139/tcp
                        - 445:445/tcp
                volumes:
                        - ./raid_fs:/mount
                command: ${SAMBA_COMMANDS}
                logging:
                        driver: fluentd
                        options:
                                fluentd-address: localhost:24224
                                tag: docker.{{.Name}}
                depends_on:
                        - fluentd
        nginx_fs:
                build:
                        context: ./nginx_fs
                        dockerfile: Dockerfile
                container_name: nginx_fs
                ports:
                        - 80:80
                volumes:
                        - ./nginx_fs/conf/conf.d:/etc/nginx/conf.d
                        - ./raid_fs:/usr/share/nginx/fs
                        - ./nginx_fs/html:/usr/share/nginx/html
                logging:
                        driver: fluentd
                        options:
                                fluentd-address: localhost:24224
                                tag: docker.{{.Name}}
                depends_on:
                        - fluentd
